import { useEffect, useState } from "react";
import { useAnalytics } from "@/hooks/useAnalytics";
import { supabase } from "@/integrations/supabase/client";
import { OverviewCards } from "@/components/analytics/OverviewCards";
import { PerformanceGraph } from "@/components/analytics/PerformanceGraph";
import { CampaignTable } from "@/components/analytics/CampaignTable";
import { GeographicMap } from "@/components/analytics/GeographicMap";
import { DeviceBreakdown } from "@/components/analytics/DeviceBreakdown";
import { HourHeatmap } from "@/components/analytics/HourHeatmap";
import { TopEvents } from "@/components/analytics/TopEvents";
import { AIInsights } from "@/components/analytics/AIInsights";
import { useSubscription } from "@/hooks/useSubscription";

export default function Analytics() {
  const [userId, setUserId] = useState<string>();
  const [dateRange, setDateRange] = useState(30);
  const { data: analytics, isLoading } = useAnalytics(userId, dateRange);
  const { subscription } = useSubscription(userId);

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => {
      setUserId(user?.id);
    });
  }, []);

  const isProPlan = subscription?.plan?.name?.toLowerCase().includes('pro') || false;

  // Sample AI insights (would be generated by GPT-4 in production)
  const sampleInsights = [
    {
      type: 'success' as const,
      title: 'Peak Performance Detected',
      description: 'Your campaigns perform 40% better between 2-4 PM. Consider scheduling more notifications during this window.',
    },
    {
      type: 'info' as const,
      title: 'Geographic Opportunity',
      description: 'Lagos accounts for 45% of your traffic but only 20% of conversions. Test localized messaging for this region.',
    },
    {
      type: 'warning' as const,
      title: 'Mobile Optimization Needed',
      description: 'Mobile CTR is 30% lower than desktop. Review your widget positioning and size for mobile devices.',
    },
  ];

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Analytics</h1>
        <p className="text-muted-foreground">
          Detailed insights about your campaigns
        </p>
      </div>

      {/* Section 1: Overview Cards */}
      <OverviewCards
        totalViews={analytics?.totalViews || 0}
        totalClicks={analytics?.totalClicks || 0}
        conversionRate={analytics?.conversionRate || 0}
        activeWidgets={analytics?.activeWidgets || 0}
        previousViews={analytics?.previousViews}
        previousClicks={analytics?.previousClicks}
        previousConversionRate={analytics?.previousConversionRate}
        previousActiveWidgets={analytics?.previousActiveWidgets}
        isLoading={isLoading}
      />

      {/* Section 2: Performance Graph */}
      <PerformanceGraph
        dailyStats={analytics?.dailyStats || []}
        dateRange={dateRange}
        onDateRangeChange={setDateRange}
        isLoading={isLoading}
      />

      {/* Section 3: Campaign Table */}
      <CampaignTable
        campaigns={analytics?.topCampaigns || []}
        isLoading={isLoading}
      />

      {/* Section 4 & 5: Geographic Map and Device Breakdown */}
      <div className="grid gap-6 md:grid-cols-2">
        <GeographicMap
          geoData={analytics?.geoData || []}
          isLoading={isLoading}
        />
        <DeviceBreakdown
          deviceData={analytics?.deviceData || []}
          isLoading={isLoading}
        />
      </div>

      {/* Section 6: Hour Heatmap */}
      <HourHeatmap
        hourlyData={analytics?.hourlyData || []}
        isLoading={isLoading}
      />

      {/* Section 7: Top Events */}
      <TopEvents
        events={analytics?.topEvents || []}
        isLoading={isLoading}
      />

      {/* Section 8: AI Insights */}
      <AIInsights
        insights={isProPlan ? sampleInsights : []}
        isProPlan={isProPlan}
        isLoading={isLoading}
      />
    </div>
  );
}
