import { useEffect, useState, useRef } from "react";
import { useAnalytics } from "@/hooks/useAnalytics";
import { supabase } from "@/integrations/supabase/client";
import { OverviewCards } from "@/components/analytics/OverviewCards";
import { PerformanceGraph } from "@/components/analytics/PerformanceGraph";
import { CampaignTable } from "@/components/analytics/CampaignTable";
import { GeographicMap } from "@/components/analytics/GeographicMap";
import { DeviceBreakdown } from "@/components/analytics/DeviceBreakdown";
import { HourHeatmap } from "@/components/analytics/HourHeatmap";
import { TopEvents } from "@/components/analytics/TopEvents";
import { AIInsights } from "@/components/analytics/AIInsights";
import { RevenueAttributionWidget } from "@/components/analytics/RevenueAttributionWidget";
import { TestimonialMetricsCard } from "@/components/analytics/TestimonialMetricsCard";
import { WebsiteSelector } from "@/components/analytics/WebsiteSelector";
import { useSubscription } from "@/hooks/useSubscription";
import { ExportButton } from "@/components/analytics/ExportButton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function Analytics() {
  const [userId, setUserId] = useState<string>();
  const [dateRange, setDateRange] = useState(30);
  const [selectedWebsite, setSelectedWebsite] = useState<string>('all');
  const { data: analytics, isLoading } = useAnalytics(
    userId, 
    dateRange, 
    selectedWebsite === 'all' ? undefined : selectedWebsite
  );
  const { subscription } = useSubscription(userId);
  const performanceChartRef = useRef<HTMLDivElement>(null);
  const geoMapRef = useRef<HTMLDivElement>(null);
  const deviceChartRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => {
      setUserId(user?.id);
    });
  }, []);

  const isProPlan = subscription?.plan?.name?.toLowerCase().includes('pro') || false;

  // Sample AI insights (would be generated by GPT-4 in production)
  const sampleInsights = [
    {
      type: 'success' as const,
      title: 'Peak Performance Detected',
      description: 'Your campaigns perform 40% better between 2-4 PM. Consider scheduling more notifications during this window.',
    },
    {
      type: 'info' as const,
      title: 'Geographic Opportunity',
      description: 'Lagos accounts for 45% of your traffic but only 20% of conversions. Test localized messaging for this region.',
    },
    {
      type: 'warning' as const,
      title: 'Mobile Optimization Needed',
      description: 'Mobile CTR is 30% lower than desktop. Review your widget positioning and size for mobile devices.',
    },
  ];

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-3xl font-bold">Analytics</h1>
          <p className="text-muted-foreground">
            Detailed insights about your campaigns
          </p>
        </div>
        <div className="flex items-center gap-4">
          <WebsiteSelector 
            userId={userId || ''} 
            value={selectedWebsite}
            onValueChange={setSelectedWebsite}
          />
          <ExportButton 
            data={analytics?.dailyStats || []} 
            filename={`analytics-${new Date().toISOString().split('T')[0]}`}
          />
        </div>
      </div>

      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="revenue">Revenue Attribution</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          {/* Section 1: Overview Cards */}
          <OverviewCards
        totalViews={analytics?.totalViews || 0}
        totalClicks={analytics?.totalClicks || 0}
        conversionRate={analytics?.conversionRate || 0}
        activeWidgets={analytics?.activeWidgets || 0}
        previousViews={analytics?.previousViews}
        previousClicks={analytics?.previousClicks}
        previousConversionRate={analytics?.previousConversionRate}
        previousActiveWidgets={analytics?.previousActiveWidgets}
        isLoading={isLoading}
      />

      {/* Testimonial Metrics - only show if there are testimonials */}
      {analytics?.testimonialMetrics && (
        <TestimonialMetricsCard 
          metrics={analytics.testimonialMetrics}
          isLoading={isLoading}
        />
      )}

      {/* Section 2: Performance Graph */}
      <div ref={performanceChartRef}>
        <PerformanceGraph
          dailyStats={analytics?.dailyStats || []}
          dateRange={dateRange}
          onDateRangeChange={setDateRange}
          isLoading={isLoading}
        />
      </div>

      {/* Section 3: Campaign Table */}
      <CampaignTable
        campaigns={analytics?.topCampaigns || []}
        isLoading={isLoading}
      />

      {/* Section 4 & 5: Geographic Map and Device Breakdown */}
      <div className="grid gap-6 md:grid-cols-2">
        <div ref={geoMapRef}>
          <GeographicMap
            geoData={analytics?.geoData || []}
            isLoading={isLoading}
          />
        </div>
        <div ref={deviceChartRef}>
          <DeviceBreakdown
            deviceData={analytics?.deviceData || []}
            isLoading={isLoading}
          />
        </div>
      </div>

      {/* Section 6: Hour Heatmap */}
      <HourHeatmap
        hourlyData={analytics?.hourlyData || []}
        isLoading={isLoading}
      />

      {/* Section 7: Top Events */}
      <TopEvents
        events={analytics?.topEvents || []}
        isLoading={isLoading}
      />

          {/* Section 8: AI Insights */}
          <AIInsights
            insights={isProPlan ? sampleInsights : []}
            isProPlan={isProPlan}
            isLoading={isLoading}
          />
        </TabsContent>

        <TabsContent value="revenue" className="space-y-6">
          <RevenueAttributionWidget userId={userId || ''} periodType="monthly" />
        </TabsContent>
      </Tabs>
    </div>
  );
}
